config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :admin do
    resources :themes
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do      
      resources :sectors
      resources :retailers
      resources :brand_owners
      resources :brands
      resources :stores
      resources :audits
    end
  end

  namespace :admin do

    get 'admin/dashboard'


    resources :settings
    resources :users
    resources :roles
    
    resources :retailers
    resources :sectors
    resources :countries

    resources :stores
    resources :channels
    resources :store_formats
    resources :environment_types
    
    resources :audits do
      resources :photos
    end
    resources :photos

    resources :categories
    resources :brand_owners
    resources :brands
    resources :media_locations
    resources :media_vehicles
    resources :media_types
    
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  # for locale

  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
  #   resources :subscribers
    root 'main#index'
  # end

  # match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
  # match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/admin/sector.rb
class Admin::Sector < ActiveRecord::Base

	has_many :retailers, :class_name => 'Admin::Retailer'
end

app/controllers/admin/sectors_controller.rb
class Admin::SectorsController < Admin::AdminController
  before_action :set_admin_sector, only: [:show, :edit, :update, :destroy]

  # GET /admin/sectors
  # GET /admin/sectors.json
  def index
    @admin_sectors = Admin::Sector.all
  end

  # GET /admin/sectors/1
  # GET /admin/sectors/1.json
  def show
  end

  # GET /admin/sectors/new
  def new
    @admin_sector = Admin::Sector.new
  end

  # GET /admin/sectors/1/edit
  def edit
  end

  # POST /admin/sectors
  # POST /admin/sectors.json
  def create
    @admin_sector = Admin::Sector.new(admin_sector_params)

    respond_to do |format|
      if @admin_sector.save
        format.html { redirect_to @admin_sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @admin_sector }
      else
        format.html { render :new }
        format.json { render json: @admin_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/sectors/1
  # PATCH/PUT /admin/sectors/1.json
  def update
    respond_to do |format|
      if @admin_sector.update(admin_sector_params)
        format.html { redirect_to @admin_sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_sector }
      else
        format.html { render :edit }
        format.json { render json: @admin_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sectors/1
  # DELETE /admin/sectors/1.json
  def destroy
    @admin_sector.destroy
    respond_to do |format|
      format.html { redirect_to admin_sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_sector
      @admin_sector = Admin::Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_sector_params
      params.require(:admin_sector).permit(:name)
    end
end

app/controllers/api/v1/sectors_controller.rb
module Api
  module V1
    class SectorsController < ApplicationController
      respond_to :json
			def index
				@sectors = Admin::Sector.all
			end
		end
	end
end

app/helpers/admin/sectors_helper.rb
module Admin::SectorsHelper
end

app/views/admin/sectors/_form.html.erb
<%= simple_form_for(@admin_sector) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/sectors/edit.html.erb
<h1>Editing admin_sector</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_sector %> |
<%= link_to 'Back', admin_sectors_path %>

app/views/admin/sectors/index.html.erb
<h1>Listing admin_sectors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_sectors.each do |admin_sector| %>
      <tr>
        <td><%= admin_sector.name %></td>
        <td><%= link_to 'Show', admin_sector %></td>
        <td><%= link_to 'Edit', edit_admin_sector_path(admin_sector) %></td>
        <td><%= link_to 'Destroy', admin_sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sector', new_admin_sector_path %>

app/views/admin/sectors/new.html.erb
<h1>New admin_sector</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sectors_path %>

app/views/admin/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_sector.name %>
</p>

<%= link_to 'Edit', edit_admin_sector_path(@admin_sector) %> |
<%= link_to 'Back', admin_sectors_path %>