config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :admin do
    resources :themes
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do      
      resources :sectors
      resources :retailers
      resources :brand_owners
      resources :brands
      resources :stores
      resources :audits
    end
  end

  namespace :admin do

    get 'admin/dashboard'


    resources :settings
    resources :users
    resources :roles
    
    resources :retailers
    resources :sectors
    resources :countries

    resources :stores
    resources :channels
    resources :store_formats
    resources :environment_types
    
    resources :audits do
      resources :photos
    end
    resources :photos

    resources :categories
    resources :brand_owners
    resources :brands
    resources :media_locations
    resources :media_vehicles
    resources :media_types
    
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  # for locale

  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
  #   resources :subscribers
    root 'main#index'
  # end

  # match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
  # match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/admin/photo.rb
class Admin::Photo < ActiveRecord::Base

 #  acts_as_paranoid
	# before_destroy :save_who_deleted

 #  def save_who_deleted
 #    # do stuff
 #  end

  belongs_to :audit, :class_name => 'Admin::Audit'

	has_attached_file :image, 
		:styles => { :large => "640x480", :medium => "300x300>", :small => "100x100>" },
		:default_url => "/images/:style/missing.png",
		:storage => :filesystem
  
  validates_attachment_presence :image
  validates_attachment_content_type :image, 
  	:content_type => ['image/jpeg', 'image/pjpeg', 
  								   'image/jpg', 'image/png']
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::AdminController
  before_action :set_admin_photo, only: [:show, :edit, :update, :destroy]
  # before_action :get_user_photos, only: [:index]

  # GET /admin/photos
  # GET /admin/photos.json
  def index
    # will only deal with user subscribed photos
    @admin_photos = Admin::Photo.all
  end

  def search
    
  end

  # GET /admin/photos/1
  # GET /admin/photos/1.json
  def show
  end

  # GET /admin/photos/new
  def new
    @admin_photo = Admin::Photo.new
  end

  # GET /admin/photos/1/edit
  def edit
  end

  # POST /admin/photos
  # POST /admin/photos.json
  def create
    @admin_photo = Admin::Photo.new(admin_photo_params)

    respond_to do |format|
      if @admin_photo.save
        format.html { redirect_to @admin_photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @admin_photo }
      else
        format.html { render :new }
        format.json { render json: @admin_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/photos/1
  # PATCH/PUT /admin/photos/1.json
  def update
    respond_to do |format|
      if @admin_photo.update(admin_photo_params)
        format.html { redirect_to @admin_photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_photo }
      else
        format.html { render :edit }
        format.json { render json: @admin_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/photos/1
  # DELETE /admin/photos/1.json
  def destroy
    @admin_photo.destroy
    respond_to do |format|
      format.html { redirect_to admin_photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_user_photos
      # check all the subscriptions

      # if user has restricted to projects
        # get only photos in the assigned projects
      
      # else
        # check from
          # section subscription
          # retailer subscription
          # category subscription

      # cache the photos for all application process until login out
      
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_photo
      @admin_photo = Admin::Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_photo_params
      params.require(:admin_photo).permit(:audit_id, :headline, :published)
    end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/views/admin/photos/_form.html.haml
= form_for @admin_photo do |f|
  - if @admin_photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_photo.errors.count, "error")} prohibited this admin_photo from being saved:"
      %ul
        - @admin_photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :audit
    = f.text_field :audit
  .field
    = f.label :headline
    = f.text_field :headline
  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/admin/photos/edit.html.haml
%h1 Editing admin_photo

= render 'form'

= link_to 'Show', @admin_photo
\|
= link_to 'Back', admin_photos_path

app/views/admin/photos/index.html.haml
%h1 Listing admin_photos

%table
  %tr
    %th Audit
    %th Headline
    %th Published
    %th
    %th
    %th

  - @admin_photos.each do |admin_photo|
    %tr
      %td= admin_photo.audit
      %td= admin_photo.headline
      %td= admin_photo.published
      %td= link_to 'Show', admin_photo
      %td= link_to 'Edit', edit_admin_photo_path(admin_photo)
      %td= link_to 'Destroy', admin_photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Photo', new_admin_photo_path

app/views/admin/photos/new.html.haml
%h1 New admin_photo

= render 'form'

= link_to 'Back', admin_photos_path

app/views/admin/photos/show.html.haml
%p#notice= notice

%p
  %b Audit:
  = @admin_photo.audit
%p
  %b Headline:
  = @admin_photo.headline
%p
  %b Published:
  = @admin_photo.published

= link_to 'Edit', edit_admin_photo_path(@admin_photo)
\|
= link_to 'Back', admin_photos_path