config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :admin do
    resources :themes
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do      
      resources :sectors
      resources :retailers
      resources :brand_owners
      resources :brands
      resources :stores
      resources :audits
    end
  end

  namespace :admin do

    get 'admin/dashboard'


    resources :settings
    resources :users
    resources :roles
    
    resources :retailers
    resources :sectors
    resources :countries

    resources :stores
    resources :channels
    resources :store_formats
    resources :environment_types
    
    resources :audits do
      resources :photos
    end
    resources :photos

    resources :categories
    resources :brand_owners
    resources :brands
    resources :media_locations
    resources :media_vehicles
    resources :media_types
    
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  # for locale

  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
  #   resources :subscribers
    root 'main#index'
  # end

  # match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
  # match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/admin/store.rb
class Admin::Store < ActiveRecord::Base

  belongs_to :store_format, :class_name => 'Admin::StoreFormat'
  belongs_to :retailer, :class_name => 'Admin::Retailer'
  belongs_to :country, :class_name => 'Admin::Country'
  belongs_to :environment_type, :class_name => 'Admin::EnvironmentType'
  belongs_to :channel, :class_name => 'Admin::Channel'

  has_many :audits, :class_name => 'Admin::Audit'
  # has_many :photos, :through => :audits

  validates :name, :presence => true
  validates :name, :uniqueness => {:message => "Store exist."}
  # validates :retailer, :presence => true
  # validates :store_format, :presence => true
  # validates :environment_type, :presence => true

  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?

  def full_address
    [address, address2, address3, town, postcode, country_name(country_id)].compact.join(', ')
  end

  def self.within_25_miles_of(geo_loc)
    near(geo_loc, 25, :order => :distance)
  end

  private

  def country_name(id)
    Admin::Country.find_by_id(id).name unless id.nil?
  end

end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::AdminController
  before_action :set_admin_store, only: [:show, :edit, :update, :destroy]

  # GET /admin/stores
  # GET /admin/stores.json
  def index
    @admin_stores = Admin::Store.all
  end

  # GET /admin/stores/1
  # GET /admin/stores/1.json
  def show
  end

  # GET /admin/stores/new
  def new
    @admin_store = Admin::Store.new
  end

  # GET /admin/stores/1/edit
  def edit
  end

  # POST /admin/stores
  # POST /admin/stores.json
  def create
    @admin_store = Admin::Store.new(admin_store_params)

    respond_to do |format|
      if @admin_store.save
        format.html { redirect_to @admin_store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @admin_store }
      else
        format.html { render :new }
        format.json { render json: @admin_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/stores/1
  # PATCH/PUT /admin/stores/1.json
  def update
    respond_to do |format|
      if @admin_store.update(admin_store_params)
        format.html { redirect_to @admin_store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_store }
      else
        format.html { render :edit }
        format.json { render json: @admin_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/stores/1
  # DELETE /admin/stores/1.json
  def destroy
    @admin_store.destroy
    respond_to do |format|
      format.html { redirect_to admin_stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_store
      @admin_store = Admin::Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_store_params
      params.require(:admin_store).permit(:name, :address, :address2, :address3, :town, :postcode, :store_format_id, :retailer_id, :country_id, :environment_type_id, :channel_id, :longitude, :latitude, :description)
    end
end

app/controllers/api/v1/stores_controller.rb
module Api
  module V1
    class StoresController < ApplicationController
      respond_to :json
			def index
				@stores = Store.all
			end
		end
	end
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/views/admin/stores/_form.html.haml
= form_for @admin_store do |f|
  - if @admin_store.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_store.errors.count, "error")} prohibited this admin_store from being saved:"
      %ul
        - @admin_store.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :address2
    = f.text_field :address2
  .field
    = f.label :address3
    = f.text_field :address3
  .field
    = f.label :town
    = f.text_field :town
  .field
    = f.label :postcode
    = f.text_field :postcode
  .field
    = f.label :store_format
    = f.text_field :store_format
  .field
    = f.label :retailer
    = f.text_field :retailer
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :environment_type
    = f.text_field :environment_type
  .field
    = f.label :channel
    = f.text_field :channel
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/admin/stores/edit.html.haml
%h1 Editing admin_store

= render 'form'

= link_to 'Show', @admin_store
\|
= link_to 'Back', admin_stores_path

app/views/admin/stores/index.html.haml
%h1 Listing admin_stores

%table
  %tr
    %th Name
    %th Address
    %th Address2
    %th Address3
    %th Town
    %th Postcode
    %th Store format
    %th Retailer
    %th Country
    %th Environment type
    %th Channel
    %th Longitude
    %th Latitude
    %th Description
    %th
    %th
    %th

  - @admin_stores.each do |admin_store|
    %tr
      %td= admin_store.name
      %td= admin_store.address
      %td= admin_store.address2
      %td= admin_store.address3
      %td= admin_store.town
      %td= admin_store.postcode
      %td= admin_store.store_format
      %td= admin_store.retailer
      %td= admin_store.country
      %td= admin_store.environment_type
      %td= admin_store.channel
      %td= admin_store.longitude
      %td= admin_store.latitude
      %td= admin_store.description
      %td= link_to 'Show', admin_store
      %td= link_to 'Edit', edit_admin_store_path(admin_store)
      %td= link_to 'Destroy', admin_store, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Store', new_admin_store_path

app/views/admin/stores/new.html.haml
%h1 New admin_store

= render 'form'

= link_to 'Back', admin_stores_path

app/views/admin/stores/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin_store.name
%p
  %b Address:
  = @admin_store.address
%p
  %b Address2:
  = @admin_store.address2
%p
  %b Address3:
  = @admin_store.address3
%p
  %b Town:
  = @admin_store.town
%p
  %b Postcode:
  = @admin_store.postcode
%p
  %b Store format:
  = @admin_store.store_format
%p
  %b Retailer:
  = @admin_store.retailer
%p
  %b Country:
  = @admin_store.country
%p
  %b Environment type:
  = @admin_store.environment_type
%p
  %b Channel:
  = @admin_store.channel
%p
  %b Longitude:
  = @admin_store.longitude
%p
  %b Latitude:
  = @admin_store.latitude
%p
  %b Description:
  = @admin_store.description

= link_to 'Edit', edit_admin_store_path(@admin_store)
\|
= link_to 'Back', admin_stores_path