config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :admin do
    resources :themes
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do      
      resources :sectors
      resources :retailers
      resources :brand_owners
      resources :brands
      resources :stores
      resources :audits
    end
  end

  namespace :admin do

    get 'admin/dashboard'


    resources :settings
    resources :users
    resources :roles
    
    resources :retailers
    resources :sectors
    resources :countries

    resources :stores
    resources :channels
    resources :store_formats
    resources :environment_types
    
    resources :audits do
      resources :photos
    end
    resources :photos

    resources :categories
    resources :brand_owners
    resources :brands
    resources :media_locations
    resources :media_vehicles
    resources :media_types
    
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  # for locale

  # scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
  #   resources :subscribers
    root 'main#index'
  # end

  # match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
  # match '', to: redirect("/#{I18n.default_locale}"), via: :get

end

app/models/admin/store_format.rb
class Admin::StoreFormat < ActiveRecord::Base
	has_many :stores, :class_name => 'Store'
end

app/controllers/admin/store_formats_controller.rb
class Admin::StoreFormatsController < Admin::AdminController
  before_action :set_admin_store_format, only: [:show, :edit, :update, :destroy]

  # GET /admin/store_formats
  # GET /admin/store_formats.json
  def index
    @admin_store_formats = Admin::StoreFormat.all
  end

  # GET /admin/store_formats/1
  # GET /admin/store_formats/1.json
  def show
  end

  # GET /admin/store_formats/new
  def new
    @admin_store_format = Admin::StoreFormat.new
  end

  # GET /admin/store_formats/1/edit
  def edit
  end

  # POST /admin/store_formats
  # POST /admin/store_formats.json
  def create
    @admin_store_format = Admin::StoreFormat.new(admin_store_format_params)

    respond_to do |format|
      if @admin_store_format.save
        format.html { redirect_to @admin_store_format, notice: 'Store format was successfully created.' }
        format.json { render :show, status: :created, location: @admin_store_format }
      else
        format.html { render :new }
        format.json { render json: @admin_store_format.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/store_formats/1
  # PATCH/PUT /admin/store_formats/1.json
  def update
    respond_to do |format|
      if @admin_store_format.update(admin_store_format_params)
        format.html { redirect_to @admin_store_format, notice: 'Store format was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_store_format }
      else
        format.html { render :edit }
        format.json { render json: @admin_store_format.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/store_formats/1
  # DELETE /admin/store_formats/1.json
  def destroy
    @admin_store_format.destroy
    respond_to do |format|
      format.html { redirect_to admin_store_formats_url, notice: 'Store format was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_store_format
      @admin_store_format = Admin::StoreFormat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_store_format_params
      params.require(:admin_store_format).permit(:name)
    end
end

app/helpers/admin/store_formats_helper.rb
module Admin::StoreFormatsHelper
end

app/views/admin/store_formats/_form.html.erb
<%= simple_form_for(@admin_store_format) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/store_formats/edit.html.erb
<h1>Editing admin_store_format</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_store_format %> |
<%= link_to 'Back', admin_store_formats_path %>

app/views/admin/store_formats/index.html.erb
<h1>Listing admin_store_formats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_store_formats.each do |admin_store_format| %>
      <tr>
        <td><%= admin_store_format.name %></td>
        <td><%= link_to 'Show', admin_store_format %></td>
        <td><%= link_to 'Edit', edit_admin_store_format_path(admin_store_format) %></td>
        <td><%= link_to 'Destroy', admin_store_format, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store format', new_admin_store_format_path %>

app/views/admin/store_formats/new.html.erb
<h1>New admin_store_format</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_store_formats_path %>

app/views/admin/store_formats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_store_format.name %>
</p>

<%= link_to 'Edit', edit_admin_store_format_path(@admin_store_format) %> |
<%= link_to 'Back', admin_store_formats_path %>